package kz.acpar.entity;
// Generated Jan 23, 2017 5:52:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userprofile generated by hbm2java
 */
@Entity
@Table(name="USERPROFILE"
    ,schema="SCOTT"
)
public class Userprofile  implements java.io.Serializable {


     private long id;
     private String login;
     private String password;
     private String email;

    public Userprofile() {
    }

	
    public Userprofile(long id) {
        this.id = id;
    }
    public Userprofile(long id, String login, String password, String email) {
       this.id = id;
       this.login = login;
       this.password = password;
       this.email = email;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="LOGIN")
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="PASSWORD")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return id + " " + login + " "+email; //To change body of generated methods, choose Tools | Templates.
    }




}


