package kz.acpar.entity;
// Generated Jan 23, 2017 5:52:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Userprofile generated by hbm2java
 */
@Entity
@Table(name="USERPROFILE",schema="SCOTT")
public class Userprofile  implements java.io.Serializable {

    @Id
    @SequenceGenerator(name = "sqnUsers", sequenceName="SQN_USERS", allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sqnUsers")
    @Column(name = "ID", nullable = false)
     private long id;
    @Column(name="LOGIN")
     private String login;
    @Column(name="PASSWORD")
     private String password;
    @Column(name="EMAIL")
     private String email;

    public Userprofile() {
    }

	

    public Userprofile( String login, String password, String email) {
       super();
       this.login = login;
       this.password = password;
       this.email = email;
    }
   
	
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return id + " " + login + " "+email; //To change body of generated methods, choose Tools | Templates.
    }




}


